name: test_workspace
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.2 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dart_fixer:
  mappings:
    models:
      jsonDir: lib/models/output/
      dartDir: lib/models/input/
      inputKind: dart
      outputKind: schema
    typedefs:
      jsonDir: lib/models/typedefs
      dartDir: lib/models/typedefs/
      inputKind: typeDefinition
